// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TKXDPM_API;

namespace TKXDPM_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201214133016_Test")]
    partial class Test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TKXDPM_API.Model.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("AddressName")
                        .HasColumnType("varchar(255)");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1001,
                            AddressName = "Phường Hạ Đình, Quận Thanh Xuân, TP Hà Nội",
                            Latitude = 100f,
                            Longitude = 99f
                        },
                        new
                        {
                            AddressId = 1002,
                            AddressName = "172 Lê Trọng Tấn, Thanh Xuân, Hà Nội",
                            Latitude = 100f,
                            Longitude = 99f
                        },
                        new
                        {
                            AddressId = 1003,
                            AddressName = "Lương Thế Vinh, Thanh Xuân, Hà Nội",
                            Latitude = 100f,
                            Longitude = 99f
                        },
                        new
                        {
                            AddressId = 1004,
                            AddressName = "Ngã tư Khuất Duy Tiến, Lê Văn Lương, Thanh Xuân, Hà Nội",
                            Latitude = 100f,
                            Longitude = 99f
                        },
                        new
                        {
                            AddressId = 1005,
                            AddressName = "57 Nguyễn Trãi, Thanh Xuân, Hà Nội",
                            Latitude = 100f,
                            Longitude = 99f
                        },
                        new
                        {
                            AddressId = 1006,
                            AddressName = "155 Trường Chinh, Khương Trung, Thanh Xuân, Hà Nội",
                            Latitude = 100f,
                            Longitude = 99f
                        });
                });

            modelBuilder.Entity("TKXDPM_API.Model.Bike", b =>
                {
                    b.Property<int>("BikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("BatterCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("BikeImage")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("BikeName")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Deposit")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("HourlyRent")
                        .HasColumnType("integer");

                    b.Property<string>("LicensePlates")
                        .HasColumnType("varchar(255)");

                    b.Property<float>("PowerDrain")
                        .HasColumnType("real");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("StartingRent")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("BikeId");

                    b.ToTable("Bikes");

                    b.HasData(
                        new
                        {
                            BikeId = 100001,
                            BatterCapacity = 0,
                            BikeImage = "https://product.hstatic.net/1000119998/product/xe-dap-the-thao-fornix-f8-4_a07b9f357957448288df8630f0f4c55d_master.jpg",
                            BikeName = "Xe đạp đua Fornix F8",
                            Deposit = 400000,
                            Description = "Với thiết kế mạnh mẽ đầy cá tính, FORNIX F8 còn mang đến cho bạn những trải nghiệm tốc độ của bộ truyền động đầy mạnh mẽ mới nhất từ thương hiệu SHIMANO.",
                            HourlyRent = 3000,
                            LicensePlates = "77A-0001",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 1
                        },
                        new
                        {
                            BikeId = 100002,
                            BatterCapacity = 0,
                            BikeImage = "https://xedapthegioi.vn/wp-content/uploads/2017/06/xe-dap-the-thao-trinx-junior-1.0-2017-1.jpg",
                            BikeName = "Xe đạp leo núi",
                            Deposit = 400000,
                            Description = "Xe Đạp Xe đạp leo núi Fat Bike của Đài Loan là một trong những chiếc xe độc đáo và mới lạ tại Việt Nam. Với đặc điểm chính là chiếc bánh xe khổng lồ tạo nên một chiếc xe khá lạ mắt.",
                            HourlyRent = 3000,
                            LicensePlates = "77A-0002",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 1
                        },
                        new
                        {
                            BikeId = 100003,
                            BatterCapacity = 0,
                            BikeImage = "https://vn-test-11.slatic.net/p/276cb18780530b969e8b4121585c409e.jpg_800x800Q100.jpg",
                            BikeName = "Xe đạp địa hình HaHoo",
                            Deposit = 400000,
                            Description = "Xe đạp HaHoo: Khung sườn xe được làm bằng hợp kim thép không gỉ, đảm bảo độ chắn chắn cho xe, có thể chịu được tải trọng của 2 người lớn. Bánh xe cực kool 26 inchs dễ dàng di chuyển với cá tính cực ngầu trong mắt mọi người.",
                            HourlyRent = 3000,
                            LicensePlates = "77A-0003",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 1
                        },
                        new
                        {
                            BikeId = 100004,
                            BatterCapacity = 0,
                            BikeImage = "https://product.hstatic.net/1000119998/product/xe-dap-the-thao-fornix-f8-4_a07b9f357957448288df8630f0f4c55d_master.jpg",
                            BikeName = "Xe đạp đua Fornix F8",
                            Deposit = 400000,
                            Description = "Với thiết kế mạnh mẽ đầy cá tính, FORNIX F8 còn mang đến cho bạn những trải nghiệm tốc độ của bộ truyền động đầy mạnh mẽ mới nhất từ thương hiệu SHIMANO.",
                            HourlyRent = 3000,
                            LicensePlates = "77A-0004",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 1
                        },
                        new
                        {
                            BikeId = 100005,
                            BatterCapacity = 0,
                            BikeImage = "https://xedapthegioi.vn/wp-content/uploads/2017/06/xe-dap-the-thao-trinx-junior-1.0-2017-1.jpg",
                            BikeName = "Xe đạp leo núi",
                            Deposit = 400000,
                            Description = "Xe Đạp Xe đạp leo núi Fat Bike của Đài Loan là một trong những chiếc xe độc đáo và mới lạ tại Việt Nam. Với đặc điểm chính là chiếc bánh xe khổng lồ tạo nên một chiếc xe khá lạ mắt.",
                            HourlyRent = 3000,
                            LicensePlates = "77A-0005",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 1
                        },
                        new
                        {
                            BikeId = 100006,
                            BatterCapacity = 0,
                            BikeImage = "https://vn-test-11.slatic.net/p/276cb18780530b969e8b4121585c409e.jpg_800x800Q100.jpg",
                            BikeName = "Xe đạp địa hình HaHoo",
                            Deposit = 400000,
                            Description = "Xe đạp HaHoo: Khung sườn xe được làm bằng hợp kim thép không gỉ, đảm bảo độ chắn chắn cho xe, có thể chịu được tải trọng của 2 người lớn. Bánh xe cực kool 26 inchs dễ dàng di chuyển với cá tính cực ngầu trong mắt mọi người.",
                            HourlyRent = 3000,
                            LicensePlates = "77A-0006",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 1
                        },
                        new
                        {
                            BikeId = 200001,
                            BatterCapacity = 0,
                            BikeImage = "https://paxbikes.com/wp-content/uploads/2020/07/xe-dap-doi-pax-6s.jpg",
                            BikeName = "XE ĐẠP ĐÔI PAX 1-SPORT",
                            Deposit = 550000,
                            Description = "Xe đạp đôi PAX 1B-SPORT màu xám có thể coi là một mẫu xe đạp đôi có thiết kế đẹp và ấn tượng của PAX kể từ trước tới nay. Ngoài thiết kế đẹp, mẫu xe đạp này còn được lắp ráp bởi các linh kiện có chất lượng tốt và đồng bộ. ",
                            HourlyRent = 3000,
                            LicensePlates = "88A-0001",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 2
                        },
                        new
                        {
                            BikeId = 200002,
                            BatterCapacity = 0,
                            BikeImage = "https://paxbikes.com/wp-content/uploads/2020/07/xe-dap-doi-pax-6b.jpg",
                            BikeName = "Xe đạp đôi PAX-2B-SPORT",
                            Deposit = 550000,
                            Description = "Thiết kế mới và tạo nên sự khác biệt hoàn toàn của xe đạp đôi PAX là hệ thống Dĩa Líp cùng nằm một bên xe, kết nối trực tiếp với nhau từ người ngồi trước và sau, điều này giúp cho người ngồi trước và ngồi sau có thể đạp tự do, tạo nên sự dễ dàng và thỏa mái khi đạp xe đạp đôi.",
                            HourlyRent = 3000,
                            LicensePlates = "88A-0002",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 2
                        },
                        new
                        {
                            BikeId = 200003,
                            BatterCapacity = 0,
                            BikeImage = "https://paxbikes.com/wp-content/uploads/2020/07/xe-dap-doi-pax-6r.jpg",
                            BikeName = "Xe đạp đôi PAX-2R-SPORT",
                            Deposit = 550000,
                            Description = "hiết kế mới và tạo nên sự khác biệt hoàn toàn của xe đạp đôi PAX là hệ thống Dĩa Líp cùng nằm một bên xe, kết nối trực tiếp với nhau từ người ngồi trước và sau, điều này giúp cho người ngồi trước và ngồi sau có thể đạp tự do, tạo nên sự dễ dàng và thỏa mái khi đạp xe đạp đôi.",
                            HourlyRent = 3000,
                            LicensePlates = "88A-0003",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 2
                        },
                        new
                        {
                            BikeId = 200004,
                            BatterCapacity = 0,
                            BikeImage = "https://paxbikes.com/wp-content/uploads/2020/07/xe-dap-doi-pax-6s.jpg",
                            BikeName = "XE ĐẠP ĐÔI PAX 1-SPORT",
                            Deposit = 550000,
                            Description = "Xe đạp đôi PAX 1B-SPORT màu xanh có thể coi là một mẫu xe đạp đôi có thiết kế đẹp và ấn tượng của PAX kể từ trước tới nay. Ngoài thiết kế đẹp, mẫu xe đạp này còn được lắp ráp bởi các linh kiện có chất lượng tốt và đồng bộ. ",
                            HourlyRent = 3000,
                            LicensePlates = "88A-0004",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 2
                        },
                        new
                        {
                            BikeId = 200005,
                            BatterCapacity = 0,
                            BikeImage = "https://paxbikes.com/wp-content/uploads/2020/07/xe-dap-doi-pax-6b.jpg",
                            BikeName = "Xe đạp đôi PAX-2B-SPORT",
                            Deposit = 550000,
                            Description = "Thiết kế mới và tạo nên sự khác biệt hoàn toàn của xe đạp đôi PAX là hệ thống Dĩa Líp cùng nằm một bên xe, kết nối trực tiếp với nhau từ người ngồi trước và sau, điều này giúp cho người ngồi trước và ngồi sau có thể đạp tự do, tạo nên sự dễ dàng và thỏa mái khi đạp xe đạp đôi.",
                            HourlyRent = 3000,
                            LicensePlates = "88A-0005",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 2
                        },
                        new
                        {
                            BikeId = 200006,
                            BatterCapacity = 0,
                            BikeImage = "https://paxbikes.com/wp-content/uploads/2020/07/xe-dap-doi-pax-6r.jpg",
                            BikeName = "Xe đạp đôi PAX-2R-SPORT",
                            Deposit = 550000,
                            Description = "hiết kế mới và tạo nên sự khác biệt hoàn toàn của xe đạp đôi PAX là hệ thống Dĩa Líp cùng nằm một bên xe, kết nối trực tiếp với nhau từ người ngồi trước và sau, điều này giúp cho người ngồi trước và ngồi sau có thể đạp tự do, tạo nên sự dễ dàng và thỏa mái khi đạp xe đạp đôi.",
                            HourlyRent = 3000,
                            LicensePlates = "88A-0006",
                            PowerDrain = 0f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 2
                        },
                        new
                        {
                            BikeId = 300001,
                            BatterCapacity = 90,
                            BikeImage = "https://salt.tikicdn.com/cache/w444/ts/product/a0/d9/c7/1576226a1ee3c162d3d3c5ab441691ec.jpg",
                            BikeName = "Xe Đạp Điện Pega Bike Zinger",
                            Deposit = 700000,
                            Description = "Bứt phá giới hạn của xe điện với 80km chỉ với 1 lần sạc .Động cơ mạnh mẽ, thỏa mãn những tay lái cừ khôi nhất.Cực kỳ an toàn nhờ phanh đĩa trước và lốp không săm.Tiết kiệm hơn 34 lần so với xe máy chạy xăng",
                            HourlyRent = 3000,
                            LicensePlates = "99A-0001",
                            PowerDrain = 300f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 3
                        },
                        new
                        {
                            BikeId = 300002,
                            BatterCapacity = 100,
                            BikeImage = "https://dailyxedien.vn/wp-content/uploads/2020/02/xe-dap-dien-cap-x-pro-update-01-768x768.jpg",
                            BikeName = "Xe Đạp Điện Bluera Cap X 2019",
                            Deposit = 700000,
                            Description = "Xe đạp điện Cap X 2019 là sản phẩm độc quyền được thiết kế và sản xuất bởi Đại Lý Xe Điện Bluera Việt Nhật. Với kiểu dáng và các màu sắc nổi bật phù hợp với mọi đối tượng sử dụng, đặc biệt Cap X 2019 sẽ bật tung phong cách cá tính riêng của các bạn trẻ tràn đầy năng lượng.",
                            HourlyRent = 3000,
                            LicensePlates = "99A-0002",
                            PowerDrain = 300f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 3
                        },
                        new
                        {
                            BikeId = 300003,
                            BatterCapacity = 80,
                            BikeImage = "https://homesheel.com.vn/wp-content/uploads/2020/07/T5S_DEN.jpg",
                            BikeName = "Xe đạp điện homesheel FTN T5s",
                            Deposit = 700000,
                            Description = "Xe điện thể thao gấp gọn Homesheel T5S vượt ra ngoài quy chuẩn thiết kế! Đẳng cấp và sang trọng tạo nên sự khác biết của NGHÀNH XE ĐIỆN",
                            HourlyRent = 3000,
                            LicensePlates = "99A-0003",
                            PowerDrain = 300f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 3
                        },
                        new
                        {
                            BikeId = 300004,
                            BatterCapacity = 90,
                            BikeImage = "https://salt.tikicdn.com/cache/w444/ts/product/a0/d9/c7/1576226a1ee3c162d3d3c5ab441691ec.jpg",
                            BikeName = "Xe Đạp Điện Pega Bike Zinger",
                            Deposit = 700000,
                            Description = "Bứt phá giới hạn của xe điện với 80km chỉ với 1 lần sạc .Động cơ mạnh mẽ, thỏa mãn những tay lái cừ khôi nhất.Cực kỳ an toàn nhờ phanh đĩa trước và lốp không săm.Tiết kiệm hơn 34 lần so với xe máy chạy xăng",
                            HourlyRent = 3000,
                            LicensePlates = "99A-0004",
                            PowerDrain = 300f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 3
                        },
                        new
                        {
                            BikeId = 300005,
                            BatterCapacity = 80,
                            BikeImage = "https://dailyxedien.vn/wp-content/uploads/2020/02/xe-dap-dien-cap-x-pro-update-01-768x768.jpg",
                            BikeName = "Xe Đạp Điện Bluera Cap X 2019",
                            Deposit = 700000,
                            Description = "Xe đạp điện Cap X 2019 là sản phẩm độc quyền được thiết kế và sản xuất bởi Đại Lý Xe Điện Bluera Việt Nhật. Với kiểu dáng và các màu sắc nổi bật phù hợp với mọi đối tượng sử dụng, đặc biệt Cap X 2019 sẽ bật tung phong cách cá tính riêng của các bạn trẻ tràn đầy năng lượng.",
                            HourlyRent = 3000,
                            LicensePlates = "99A-0005",
                            PowerDrain = 300f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 3
                        },
                        new
                        {
                            BikeId = 300006,
                            BatterCapacity = 80,
                            BikeImage = "https://homesheel.com.vn/wp-content/uploads/2020/07/T5S_DEN.jpg",
                            BikeName = "Xe đạp điện homesheel FTN T5s",
                            Deposit = 700000,
                            Description = "Xe điện thể thao gấp gọn Homesheel T5S vượt ra ngoài quy chuẩn thiết kế! Đẳng cấp và sang trọng tạo nên sự khác biết của NGHÀNH XE ĐIỆN",
                            HourlyRent = 3000,
                            LicensePlates = "99A-0006",
                            PowerDrain = 300f,
                            Size = 26,
                            StartingRent = 10000,
                            Type = 3
                        });
                });

            modelBuilder.Entity("TKXDPM_API.Model.BikeInStation", b =>
                {
                    b.Property<int>("BikeId")
                        .HasColumnType("integer");

                    b.Property<int>("StationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTimeIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateTimeOut")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("BikeId", "StationId");

                    b.HasIndex("StationId");

                    b.ToTable("BikeInStations");

                    b.HasData(
                        new
                        {
                            BikeId = 100001,
                            StationId = 1001,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 100002,
                            StationId = 1001,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 200001,
                            StationId = 1001,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 300001,
                            StationId = 1001,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 100003,
                            StationId = 1002,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 100004,
                            StationId = 1002,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 200002,
                            StationId = 1002,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 300002,
                            StationId = 1002,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 100005,
                            StationId = 1003,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 100006,
                            StationId = 1003,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 200003,
                            StationId = 1003,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 300003,
                            StationId = 1003,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 200004,
                            StationId = 1004,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 200005,
                            StationId = 1004,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 300004,
                            StationId = 1004,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 300005,
                            StationId = 1004,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 200006,
                            StationId = 1005,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BikeId = 300006,
                            StationId = 1005,
                            DateTimeIn = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTimeOut = new DateTime(2020, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TKXDPM_API.Model.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("CardCode")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Cvv")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RenterId")
                        .HasColumnType("integer");

                    b.HasKey("CardId");

                    b.HasIndex("RenterId")
                        .IsUnique();

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 100001,
                            CardCode = "118609_group4_2020",
                            Cvv = 228,
                            ExpirationDate = new DateTime(2020, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "PaymentMethod",
                            RenterId = 100001
                        },
                        new
                        {
                            CardId = 100002,
                            CardCode = "118609_group5_2020",
                            Cvv = 234,
                            ExpirationDate = new DateTime(2020, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "PaymentMethod",
                            RenterId = 100002
                        },
                        new
                        {
                            CardId = 100003,
                            CardCode = "118609_group6_2020",
                            Cvv = 563,
                            ExpirationDate = new DateTime(2020, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "PaymentMethod",
                            RenterId = 100003
                        },
                        new
                        {
                            CardId = 100004,
                            CardCode = "118609_group7_2020",
                            Cvv = 463,
                            ExpirationDate = new DateTime(2020, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "PaymentMethod",
                            RenterId = 100004
                        },
                        new
                        {
                            CardId = 100005,
                            CardCode = "118609_group8_2020",
                            Cvv = 263,
                            ExpirationDate = new DateTime(2020, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "PaymentMethod",
                            RenterId = 100005
                        },
                        new
                        {
                            CardId = 100006,
                            CardCode = "118609_group9_2020",
                            Cvv = 262,
                            ExpirationDate = new DateTime(2020, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "PaymentMethod",
                            RenterId = 100006
                        });
                });

            modelBuilder.Entity("TKXDPM_API.Model.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("BikeId")
                        .HasColumnType("integer");

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<string>("RateContent")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RateNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RenterId")
                        .HasColumnType("integer");

                    b.HasKey("RentalId");

                    b.HasIndex("BikeId");

                    b.HasIndex("CardId");

                    b.HasIndex("RenterId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            RentalId = 100001,
                            BikeId = 100001,
                            CardId = 100001,
                            RateContent = "Mọi thứ đều tốt.",
                            RateNumber = 5,
                            RenterId = 100001
                        },
                        new
                        {
                            RentalId = 100002,
                            BikeId = 100002,
                            CardId = 100002,
                            RateContent = "Tuyệt vời.",
                            RateNumber = 5,
                            RenterId = 100002
                        },
                        new
                        {
                            RentalId = 100003,
                            BikeId = 200001,
                            CardId = 100003,
                            RateContent = "Mọi thứ đều tốt.",
                            RateNumber = 5,
                            RenterId = 100003
                        },
                        new
                        {
                            RentalId = 100004,
                            BikeId = 200002,
                            CardId = 100001,
                            RateContent = "Xe đi rất thoải mái.",
                            RateNumber = 4,
                            RenterId = 100004
                        },
                        new
                        {
                            RentalId = 100005,
                            BikeId = 300001,
                            CardId = 100001,
                            RateContent = "Mọi thứ đều tốt.",
                            RateNumber = 5,
                            RenterId = 100005
                        },
                        new
                        {
                            RentalId = 100006,
                            BikeId = 100004,
                            CardId = 100001,
                            RateContent = "Trải nghiệm thú vị.",
                            RateNumber = 5,
                            RenterId = 100006
                        });
                });

            modelBuilder.Entity("TKXDPM_API.Model.Renter", b =>
                {
                    b.Property<int>("RenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("DeviceCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("RenterId");

                    b.ToTable("Renters");

                    b.HasData(
                        new
                        {
                            RenterId = 100001,
                            DeviceCode = "5c9a7697-1ab7-4025-a8b1-73eeed009893",
                            Name = "Group 4"
                        },
                        new
                        {
                            RenterId = 100002,
                            DeviceCode = "eba903d4-3a38-4acf-a566-487f0bb21e8b",
                            Name = "Nguyễn Văn Linh"
                        },
                        new
                        {
                            RenterId = 100003,
                            DeviceCode = "4e8eb23d-316d-48ae-8703-a28ca5fb9fd1",
                            Name = "Phạm Huy Hoàng"
                        },
                        new
                        {
                            RenterId = 100004,
                            DeviceCode = "b89570dd-9ae3-4317-b610-6de2b548764c",
                            Name = "Trần Đình Đức"
                        },
                        new
                        {
                            RenterId = 100005,
                            DeviceCode = "8a09d153-e9c7-4a77-abc9-23b014cb3edc",
                            Name = "Vũ Duy Tiến"
                        },
                        new
                        {
                            RenterId = 100006,
                            DeviceCode = "2ade6a42-e744-4c3a-a9e8-263a47920f63",
                            Name = "Phạm Mạnh Cường"
                        },
                        new
                        {
                            RenterId = 100007,
                            DeviceCode = "d8f539f4-14d9-43dc-ad81-40def84cc26e",
                            Name = "Trần Văn Tâm"
                        },
                        new
                        {
                            RenterId = 100008,
                            DeviceCode = "3c063b4d-2986-4591-8ee5-7116e9c17f79",
                            Name = "Khổng Hoàng Phong"
                        });
                });

            modelBuilder.Entity("TKXDPM_API.Model.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<float>("Area")
                        .HasColumnType("real");

                    b.Property<string>("ContactName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StationImage")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("StationName")
                        .HasColumnType("varchar(255)");

                    b.HasKey("StationId");

                    b.HasIndex("AddressId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationId = 1001,
                            AddressId = 1001,
                            Area = 500f,
                            ContactName = "Nguyễn Anh Dũng",
                            Email = "aeon.ecopark@gmail.ccom",
                            Phone = "0906232138",
                            StationImage = "https://ecoparker.s3.ap-southeast-1.amazonaws.com/s3fs-public/styles/8_col/public/nha%20hang/starbucks-ecopark-13.jpg?itok=Pvth7skq",
                            StationName = "Starbuck Ecopark"
                        },
                        new
                        {
                            StationId = 1002,
                            AddressId = 1002,
                            Area = 500f,
                            ContactName = "Nguyễn Mạnh Hùng",
                            Email = "tennis.ecopark@gmail.com",
                            Phone = "0962610374",
                            StationImage = "http://ecoparksupport.com/wp-content/uploads/2020/05/san-golf-ecopark-1.jpg",
                            StationName = "Sân Golf Rừng Cọ - Ecopark"
                        },
                        new
                        {
                            StationId = 1003,
                            AddressId = 1003,
                            Area = 500f,
                            ContactName = "Ngọ Anh Cường",
                            Email = "springpark.ecopark@gmail.com",
                            Phone = "0936656669",
                            StationImage = "https://ecoparker.s3.ap-southeast-1.amazonaws.com/s3fs-public/pictures/cong-vien-ho-thien-nga-ecopark-1.jpg",
                            StationName = "Công viên mùa xuân - Spring Park"
                        },
                        new
                        {
                            StationId = 1004,
                            AddressId = 1004,
                            Area = 500f,
                            ContactName = "Vũ Hữu Đạt",
                            Email = "summerpark.ecopark@gmail.com",
                            Phone = "0466519528",
                            StationImage = "https://ecoparker.s3.ap-southeast-1.amazonaws.com/choi/cong-vien-mua-ha-ecopark-02.jpg",
                            StationName = "Công viên mùa hạ"
                        },
                        new
                        {
                            StationId = 1005,
                            AddressId = 1005,
                            Area = 500f,
                            ContactName = "Nguyễn Đình Thắng",
                            Email = "winterpark.ecopark@gmail.com",
                            Phone = "0987866389",
                            StationImage = "https://ecoparker.s3.ap-southeast-1.amazonaws.com/choi/cung-duong-ecopark-grand-10.jpg",
                            StationName = "Công viên mùa đông"
                        },
                        new
                        {
                            StationId = 1006,
                            AddressId = 1006,
                            Area = 500f,
                            ContactName = "Trương Anh Minh",
                            Email = "autumpark.ecopark@gmail.com",
                            Phone = "0987866389",
                            StationImage = "https://datvietvnn.com/wp-content/uploads/2020/05/cong-vien-mua-ha-ecopark.jpg",
                            StationName = "Công viên mùa thu"
                        });
                });

            modelBuilder.Entity("TKXDPM_API.Model.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("ActualEndDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ActualStartDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("BookedEndDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("BookedStartDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("RentalId")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("RentalId")
                        .IsUnique();

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 100001,
                            ActualEndDateTime = new DateTime(2020, 12, 3, 10, 14, 54, 0, DateTimeKind.Unspecified),
                            ActualStartDateTime = new DateTime(2020, 12, 3, 8, 32, 54, 0, DateTimeKind.Unspecified),
                            BookedEndDateTime = new DateTime(2020, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookedStartDateTime = new DateTime(2020, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = 2,
                            RentalId = 100001
                        },
                        new
                        {
                            TransactionId = 100002,
                            ActualEndDateTime = new DateTime(2020, 12, 3, 10, 14, 54, 0, DateTimeKind.Unspecified),
                            ActualStartDateTime = new DateTime(2020, 12, 3, 8, 32, 54, 0, DateTimeKind.Unspecified),
                            BookedEndDateTime = new DateTime(2020, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookedStartDateTime = new DateTime(2020, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = 3,
                            RentalId = 100001
                        },
                        new
                        {
                            TransactionId = 100003,
                            ActualEndDateTime = new DateTime(2020, 12, 3, 10, 14, 54, 0, DateTimeKind.Unspecified),
                            ActualStartDateTime = new DateTime(2020, 12, 3, 8, 32, 54, 0, DateTimeKind.Unspecified),
                            BookedEndDateTime = new DateTime(2020, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookedStartDateTime = new DateTime(2020, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = 1,
                            RentalId = 100001
                        },
                        new
                        {
                            TransactionId = 100004,
                            ActualEndDateTime = new DateTime(2020, 12, 3, 10, 14, 54, 0, DateTimeKind.Unspecified),
                            ActualStartDateTime = new DateTime(2020, 12, 3, 8, 32, 54, 0, DateTimeKind.Unspecified),
                            BookedEndDateTime = new DateTime(2020, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookedStartDateTime = new DateTime(2020, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = 3,
                            RentalId = 100002
                        });
                });

            modelBuilder.Entity("TKXDPM_API.Model.BikeInStation", b =>
                {
                    b.HasOne("TKXDPM_API.Model.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TKXDPM_API.Model.Station", "Station")
                        .WithMany("BikeInStations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TKXDPM_API.Model.Card", b =>
                {
                    b.HasOne("TKXDPM_API.Model.Renter", "Renter")
                        .WithOne("Card")
                        .HasForeignKey("TKXDPM_API.Model.Card", "RenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("TKXDPM_API.Model.Rental", b =>
                {
                    b.HasOne("TKXDPM_API.Model.Bike", "Bike")
                        .WithMany("Rentals")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TKXDPM_API.Model.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TKXDPM_API.Model.Renter", "Renter")
                        .WithMany("Rentals")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Card");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("TKXDPM_API.Model.Station", b =>
                {
                    b.HasOne("TKXDPM_API.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("TKXDPM_API.Model.Transaction", b =>
                {
                    b.HasOne("TKXDPM_API.Model.Rental", "Rental")
                        .WithOne("Transaction")
                        .HasForeignKey("TKXDPM_API.Model.Transaction", "RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("TKXDPM_API.Model.Bike", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("TKXDPM_API.Model.Rental", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TKXDPM_API.Model.Renter", b =>
                {
                    b.Navigation("Card");

                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("TKXDPM_API.Model.Station", b =>
                {
                    b.Navigation("BikeInStations");
                });
#pragma warning restore 612, 618
        }
    }
}
